services:
  banner-rotation:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "25433:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banner_rotation -d banner_rotation"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    env_file: .env
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"    # AMQP
      - "${RABBITMQ_WEB_PORT}:${RABBITMQ_WEB_PORT}"    # Web UI
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: