// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: bannerrotation/bannerrotation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int64                  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	BannerId      int64                  `protobuf:"varint,2,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBannerRequest) Reset() {
	*x = AddBannerRequest{}
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBannerRequest) ProtoMessage() {}

func (x *AddBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBannerRequest.ProtoReflect.Descriptor instead.
func (*AddBannerRequest) Descriptor() ([]byte, []int) {
	return file_bannerrotation_bannerrotation_proto_rawDescGZIP(), []int{0}
}

func (x *AddBannerRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *AddBannerRequest) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

type AddBannerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBannerResponse) Reset() {
	*x = AddBannerResponse{}
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBannerResponse) ProtoMessage() {}

func (x *AddBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBannerResponse.ProtoReflect.Descriptor instead.
func (*AddBannerResponse) Descriptor() ([]byte, []int) {
	return file_bannerrotation_bannerrotation_proto_rawDescGZIP(), []int{1}
}

type RemoveBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int64                  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	BannerId      int64                  `protobuf:"varint,2,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBannerRequest) Reset() {
	*x = RemoveBannerRequest{}
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBannerRequest) ProtoMessage() {}

func (x *RemoveBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBannerRequest.ProtoReflect.Descriptor instead.
func (*RemoveBannerRequest) Descriptor() ([]byte, []int) {
	return file_bannerrotation_bannerrotation_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveBannerRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *RemoveBannerRequest) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

type RemoveBannerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBannerResponse) Reset() {
	*x = RemoveBannerResponse{}
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBannerResponse) ProtoMessage() {}

func (x *RemoveBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBannerResponse.ProtoReflect.Descriptor instead.
func (*RemoveBannerResponse) Descriptor() ([]byte, []int) {
	return file_bannerrotation_bannerrotation_proto_rawDescGZIP(), []int{3}
}

type RegisterClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int64                  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	BannerId      int64                  `protobuf:"varint,2,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	SocialGroupId int64                  `protobuf:"varint,3,opt,name=social_group_id,json=socialGroupId,proto3" json:"social_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClickRequest) Reset() {
	*x = RegisterClickRequest{}
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClickRequest) ProtoMessage() {}

func (x *RegisterClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClickRequest.ProtoReflect.Descriptor instead.
func (*RegisterClickRequest) Descriptor() ([]byte, []int) {
	return file_bannerrotation_bannerrotation_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterClickRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *RegisterClickRequest) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *RegisterClickRequest) GetSocialGroupId() int64 {
	if x != nil {
		return x.SocialGroupId
	}
	return 0
}

type RegisterClickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClickResponse) Reset() {
	*x = RegisterClickResponse{}
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClickResponse) ProtoMessage() {}

func (x *RegisterClickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClickResponse.ProtoReflect.Descriptor instead.
func (*RegisterClickResponse) Descriptor() ([]byte, []int) {
	return file_bannerrotation_bannerrotation_proto_rawDescGZIP(), []int{5}
}

type GetBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int64                  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	SocialGroupId int64                  `protobuf:"varint,2,opt,name=social_group_id,json=socialGroupId,proto3" json:"social_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBannerRequest) Reset() {
	*x = GetBannerRequest{}
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannerRequest) ProtoMessage() {}

func (x *GetBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannerRequest.ProtoReflect.Descriptor instead.
func (*GetBannerRequest) Descriptor() ([]byte, []int) {
	return file_bannerrotation_bannerrotation_proto_rawDescGZIP(), []int{6}
}

func (x *GetBannerRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *GetBannerRequest) GetSocialGroupId() int64 {
	if x != nil {
		return x.SocialGroupId
	}
	return 0
}

type GetBannerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannerId      int64                  `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBannerResponse) Reset() {
	*x = GetBannerResponse{}
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannerResponse) ProtoMessage() {}

func (x *GetBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bannerrotation_bannerrotation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannerResponse.ProtoReflect.Descriptor instead.
func (*GetBannerResponse) Descriptor() ([]byte, []int) {
	return file_bannerrotation_bannerrotation_proto_rawDescGZIP(), []int{7}
}

func (x *GetBannerResponse) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

var File_bannerrotation_bannerrotation_proto protoreflect.FileDescriptor

const file_bannerrotation_bannerrotation_proto_rawDesc = "" +
	"\n" +
	"#bannerrotation/bannerrotation.proto\x12\x0ebannerrotation\"H\n" +
	"\x10AddBannerRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x03R\x06slotId\x12\x1b\n" +
	"\tbanner_id\x18\x02 \x01(\x03R\bbannerId\"\x13\n" +
	"\x11AddBannerResponse\"K\n" +
	"\x13RemoveBannerRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x03R\x06slotId\x12\x1b\n" +
	"\tbanner_id\x18\x02 \x01(\x03R\bbannerId\"\x16\n" +
	"\x14RemoveBannerResponse\"t\n" +
	"\x14RegisterClickRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x03R\x06slotId\x12\x1b\n" +
	"\tbanner_id\x18\x02 \x01(\x03R\bbannerId\x12&\n" +
	"\x0fsocial_group_id\x18\x03 \x01(\x03R\rsocialGroupId\"\x17\n" +
	"\x15RegisterClickResponse\"S\n" +
	"\x10GetBannerRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x03R\x06slotId\x12&\n" +
	"\x0fsocial_group_id\x18\x02 \x01(\x03R\rsocialGroupId\"0\n" +
	"\x11GetBannerResponse\x12\x1b\n" +
	"\tbanner_id\x18\x01 \x01(\x03R\bbannerId2\xfb\x02\n" +
	"\x15BannerRotationService\x12P\n" +
	"\tAddBanner\x12 .bannerrotation.AddBannerRequest\x1a!.bannerrotation.AddBannerResponse\x12Y\n" +
	"\fRemoveBanner\x12#.bannerrotation.RemoveBannerRequest\x1a$.bannerrotation.RemoveBannerResponse\x12\\\n" +
	"\rRegisterClick\x12$.bannerrotation.RegisterClickRequest\x1a%.bannerrotation.RegisterClickResponse\x12W\n" +
	"\x10GetBannerForSlot\x12 .bannerrotation.GetBannerRequest\x1a!.bannerrotation.GetBannerResponseBJZHgithub.com/AndreyNagorskiy/otus-banner-rotation/pb/api/bannerrotation;pbb\x06proto3"

var (
	file_bannerrotation_bannerrotation_proto_rawDescOnce sync.Once
	file_bannerrotation_bannerrotation_proto_rawDescData []byte
)

func file_bannerrotation_bannerrotation_proto_rawDescGZIP() []byte {
	file_bannerrotation_bannerrotation_proto_rawDescOnce.Do(func() {
		file_bannerrotation_bannerrotation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bannerrotation_bannerrotation_proto_rawDesc), len(file_bannerrotation_bannerrotation_proto_rawDesc)))
	})
	return file_bannerrotation_bannerrotation_proto_rawDescData
}

var file_bannerrotation_bannerrotation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bannerrotation_bannerrotation_proto_goTypes = []any{
	(*AddBannerRequest)(nil),      // 0: bannerrotation.AddBannerRequest
	(*AddBannerResponse)(nil),     // 1: bannerrotation.AddBannerResponse
	(*RemoveBannerRequest)(nil),   // 2: bannerrotation.RemoveBannerRequest
	(*RemoveBannerResponse)(nil),  // 3: bannerrotation.RemoveBannerResponse
	(*RegisterClickRequest)(nil),  // 4: bannerrotation.RegisterClickRequest
	(*RegisterClickResponse)(nil), // 5: bannerrotation.RegisterClickResponse
	(*GetBannerRequest)(nil),      // 6: bannerrotation.GetBannerRequest
	(*GetBannerResponse)(nil),     // 7: bannerrotation.GetBannerResponse
}
var file_bannerrotation_bannerrotation_proto_depIdxs = []int32{
	0, // 0: bannerrotation.BannerRotationService.AddBanner:input_type -> bannerrotation.AddBannerRequest
	2, // 1: bannerrotation.BannerRotationService.RemoveBanner:input_type -> bannerrotation.RemoveBannerRequest
	4, // 2: bannerrotation.BannerRotationService.RegisterClick:input_type -> bannerrotation.RegisterClickRequest
	6, // 3: bannerrotation.BannerRotationService.GetBannerForSlot:input_type -> bannerrotation.GetBannerRequest
	1, // 4: bannerrotation.BannerRotationService.AddBanner:output_type -> bannerrotation.AddBannerResponse
	3, // 5: bannerrotation.BannerRotationService.RemoveBanner:output_type -> bannerrotation.RemoveBannerResponse
	5, // 6: bannerrotation.BannerRotationService.RegisterClick:output_type -> bannerrotation.RegisterClickResponse
	7, // 7: bannerrotation.BannerRotationService.GetBannerForSlot:output_type -> bannerrotation.GetBannerResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bannerrotation_bannerrotation_proto_init() }
func file_bannerrotation_bannerrotation_proto_init() {
	if File_bannerrotation_bannerrotation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bannerrotation_bannerrotation_proto_rawDesc), len(file_bannerrotation_bannerrotation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bannerrotation_bannerrotation_proto_goTypes,
		DependencyIndexes: file_bannerrotation_bannerrotation_proto_depIdxs,
		MessageInfos:      file_bannerrotation_bannerrotation_proto_msgTypes,
	}.Build()
	File_bannerrotation_bannerrotation_proto = out.File
	file_bannerrotation_bannerrotation_proto_goTypes = nil
	file_bannerrotation_bannerrotation_proto_depIdxs = nil
}
