// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: bannerrotation/bannerrotation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BannerRotationService_AddBanner_FullMethodName        = "/bannerrotation.BannerRotationService/AddBanner"
	BannerRotationService_RemoveBanner_FullMethodName     = "/bannerrotation.BannerRotationService/RemoveBanner"
	BannerRotationService_RegisterClick_FullMethodName    = "/bannerrotation.BannerRotationService/RegisterClick"
	BannerRotationService_GetBannerForSlot_FullMethodName = "/bannerrotation.BannerRotationService/GetBannerForSlot"
)

// BannerRotationServiceClient is the client API for BannerRotationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BannerRotationServiceClient interface {
	AddBanner(ctx context.Context, in *AddBannerRequest, opts ...grpc.CallOption) (*AddBannerResponse, error)
	RemoveBanner(ctx context.Context, in *RemoveBannerRequest, opts ...grpc.CallOption) (*RemoveBannerResponse, error)
	RegisterClick(ctx context.Context, in *RegisterClickRequest, opts ...grpc.CallOption) (*RegisterClickResponse, error)
	GetBannerForSlot(ctx context.Context, in *GetBannerRequest, opts ...grpc.CallOption) (*GetBannerResponse, error)
}

type bannerRotationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBannerRotationServiceClient(cc grpc.ClientConnInterface) BannerRotationServiceClient {
	return &bannerRotationServiceClient{cc}
}

func (c *bannerRotationServiceClient) AddBanner(ctx context.Context, in *AddBannerRequest, opts ...grpc.CallOption) (*AddBannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBannerResponse)
	err := c.cc.Invoke(ctx, BannerRotationService_AddBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerRotationServiceClient) RemoveBanner(ctx context.Context, in *RemoveBannerRequest, opts ...grpc.CallOption) (*RemoveBannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBannerResponse)
	err := c.cc.Invoke(ctx, BannerRotationService_RemoveBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerRotationServiceClient) RegisterClick(ctx context.Context, in *RegisterClickRequest, opts ...grpc.CallOption) (*RegisterClickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterClickResponse)
	err := c.cc.Invoke(ctx, BannerRotationService_RegisterClick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerRotationServiceClient) GetBannerForSlot(ctx context.Context, in *GetBannerRequest, opts ...grpc.CallOption) (*GetBannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBannerResponse)
	err := c.cc.Invoke(ctx, BannerRotationService_GetBannerForSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BannerRotationServiceServer is the server API for BannerRotationService service.
// All implementations must embed UnimplementedBannerRotationServiceServer
// for forward compatibility.
type BannerRotationServiceServer interface {
	AddBanner(context.Context, *AddBannerRequest) (*AddBannerResponse, error)
	RemoveBanner(context.Context, *RemoveBannerRequest) (*RemoveBannerResponse, error)
	RegisterClick(context.Context, *RegisterClickRequest) (*RegisterClickResponse, error)
	GetBannerForSlot(context.Context, *GetBannerRequest) (*GetBannerResponse, error)
	mustEmbedUnimplementedBannerRotationServiceServer()
}

// UnimplementedBannerRotationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBannerRotationServiceServer struct{}

func (UnimplementedBannerRotationServiceServer) AddBanner(context.Context, *AddBannerRequest) (*AddBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBanner not implemented")
}
func (UnimplementedBannerRotationServiceServer) RemoveBanner(context.Context, *RemoveBannerRequest) (*RemoveBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBanner not implemented")
}
func (UnimplementedBannerRotationServiceServer) RegisterClick(context.Context, *RegisterClickRequest) (*RegisterClickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterClick not implemented")
}
func (UnimplementedBannerRotationServiceServer) GetBannerForSlot(context.Context, *GetBannerRequest) (*GetBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBannerForSlot not implemented")
}
func (UnimplementedBannerRotationServiceServer) mustEmbedUnimplementedBannerRotationServiceServer() {}
func (UnimplementedBannerRotationServiceServer) testEmbeddedByValue()                               {}

// UnsafeBannerRotationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BannerRotationServiceServer will
// result in compilation errors.
type UnsafeBannerRotationServiceServer interface {
	mustEmbedUnimplementedBannerRotationServiceServer()
}

func RegisterBannerRotationServiceServer(s grpc.ServiceRegistrar, srv BannerRotationServiceServer) {
	// If the following call pancis, it indicates UnimplementedBannerRotationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BannerRotationService_ServiceDesc, srv)
}

func _BannerRotationService_AddBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerRotationServiceServer).AddBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BannerRotationService_AddBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerRotationServiceServer).AddBanner(ctx, req.(*AddBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerRotationService_RemoveBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerRotationServiceServer).RemoveBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BannerRotationService_RemoveBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerRotationServiceServer).RemoveBanner(ctx, req.(*RemoveBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerRotationService_RegisterClick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerRotationServiceServer).RegisterClick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BannerRotationService_RegisterClick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerRotationServiceServer).RegisterClick(ctx, req.(*RegisterClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerRotationService_GetBannerForSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerRotationServiceServer).GetBannerForSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BannerRotationService_GetBannerForSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerRotationServiceServer).GetBannerForSlot(ctx, req.(*GetBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BannerRotationService_ServiceDesc is the grpc.ServiceDesc for BannerRotationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BannerRotationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bannerrotation.BannerRotationService",
	HandlerType: (*BannerRotationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBanner",
			Handler:    _BannerRotationService_AddBanner_Handler,
		},
		{
			MethodName: "RemoveBanner",
			Handler:    _BannerRotationService_RemoveBanner_Handler,
		},
		{
			MethodName: "RegisterClick",
			Handler:    _BannerRotationService_RegisterClick_Handler,
		},
		{
			MethodName: "GetBannerForSlot",
			Handler:    _BannerRotationService_GetBannerForSlot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bannerrotation/bannerrotation.proto",
}
